import { useState } from 'react';
import { motion } from 'motion/react';
import {
  ArrowLeft,
  Download,
  Share2,
  FileText,
  Calendar,
  User,
  Eye,
  TrendingUp,
  TrendingDown,
  Minus,
  BarChart3,
  PieChart,
  LineChart,
  CheckCircle,
  Lightbulb,
  Target
} from 'lucide-react';
import { Report } from '../../data/reportsData';
import {
  BarChart,
  Bar,
  LineChart as ReLineChart,
  Line,
  PieChart as RePieChart,
  Pie,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Cell
} from 'recharts';

interface ReportDetailProps {
  report: Report;
  onBack: () => void;
}

export function ReportDetail({ report, onBack }: ReportDetailProps) {
  const [selectedFormat, setSelectedFormat] = useState(report.format[0]);

  const getTrendIcon = (trend?: 'up' | 'down' | 'stable') => {
    if (trend === 'up') return <TrendingUp size={16} className="text-green-600" />;
    if (trend === 'down') return <TrendingDown size={16} className="text-red-600" />;
    return <Minus size={16} className="text-slate-400" />;
  };

  // Prepare chart data
  const prepareChartData = () => {
    if (!report.chartData) return [];
    
    if (report.chartData.type === 'pie') {
      return report.chartData.labels.map((label, idx) => ({
        name: label,
        value: report.chartData!.datasets[0].data[idx]
      }));
    }
    
    return report.chartData.labels.map((label, idx) => {
      const dataPoint: any = { name: label };
      report.chartData!.datasets.forEach((dataset) => {
        dataPoint[dataset.label] = dataset.data[idx];
      });
      return dataPoint;
    });
  };

  const chartData = prepareChartData();
  const COLORS = ['#10b981', '#3b82f6', '#8b5cf6', '#f59e0b', '#ef4444', '#06b6d4'];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="space-y-4 sm:space-y-6"
    >
      {/* Header */}
      <div className="glass-card-darker rounded-2xl p-4 sm:p-6">
        <div className="flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6">
          <button
            onClick={onBack}
            className="w-10 h-10 rounded-xl bg-white/70 hover:bg-white border border-white/30 flex items-center justify-center transition-all flex-shrink-0"
          >
            <ArrowLeft size={20} />
          </button>
          <div className="flex-1 min-w-0">
            <h2 className="text-slate-900 mb-1">Report Details</h2>
            <p className="text-sm text-slate-600 font-odia">ରିପୋର୍ଟ ବିବରଣୀ</p>
          </div>
          <div className="hidden sm:flex gap-2">
            <button className="px-4 py-2 rounded-xl bg-white/70 hover:bg-white border border-white/30 flex items-center gap-2 transition-all">
              <Share2 size={18} />
              <span className="text-sm">Share</span>
            </button>
          </div>
        </div>

        {/* Title */}
        <h3 className="text-slate-900 mb-2">{report.title}</h3>
        <p className="text-sm text-slate-600 font-odia mb-4">{report.titleOdia}</p>
        
        {/* Description */}
        <p className="text-sm sm:text-base text-slate-700 mb-3">{report.description}</p>
        <p className="text-sm text-slate-600 font-odia">{report.descriptionOdia}</p>
      </div>

      {/* Meta Information */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <div className="glass-card rounded-xl p-3 sm:p-4">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="text-green-600" size={18} />
            <span className="text-xs sm:text-sm text-slate-600">Report ID</span>
          </div>
          <p className="text-sm sm:text-base text-slate-900 font-mono">{report.reportId}</p>
        </div>

        <div className="glass-card rounded-xl p-3 sm:p-4">
          <div className="flex items-center gap-2 mb-2">
            <Calendar className="text-blue-600" size={18} />
            <span className="text-xs sm:text-sm text-slate-600">Period</span>
          </div>
          <p className="text-sm sm:text-base text-slate-900">{report.period}</p>
          <p className="text-xs text-slate-600 font-odia">{report.periodOdia}</p>
        </div>

        <div className="glass-card rounded-xl p-3 sm:p-4">
          <div className="flex items-center gap-2 mb-2">
            <User className="text-purple-600" size={18} />
            <span className="text-xs sm:text-sm text-slate-600">Generated By</span>
          </div>
          <p className="text-sm sm:text-base text-slate-900 line-clamp-2">{report.generatedBy}</p>
        </div>

        <div className="glass-card rounded-xl p-3 sm:p-4">
          <div className="flex items-center gap-2 mb-2">
            <Eye className="text-amber-600" size={18} />
            <span className="text-xs sm:text-sm text-slate-600">Views</span>
          </div>
          <p className="text-xl sm:text-2xl text-slate-900 font-mono">{report.views.toLocaleString()}</p>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="glass-card rounded-2xl p-4 sm:p-6">
        <h3 className="text-slate-800 mb-4 flex items-center gap-2">
          <BarChart3 size={20} />
          Key Metrics
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 sm:gap-4">
          {report.metrics.map((metric, idx) => (
            <div key={idx} className="p-3 sm:p-4 bg-white/50 rounded-xl">
              <p className="text-xs text-slate-600 mb-2 line-clamp-2">{metric.label}</p>
              <p className="text-base sm:text-lg font-mono font-medium text-slate-900 mb-1">
                {typeof metric.value === 'number' ? metric.value.toLocaleString() : metric.value}
              </p>
              {metric.change !== undefined && (
                <div className="flex items-center gap-1">
                  {getTrendIcon(metric.trend)}
                  <span className={`text-xs font-mono ${
                    metric.trend === 'up' ? 'text-green-600' : 
                    metric.trend === 'down' ? 'text-red-600' : 'text-slate-400'
                  }`}>
                    {metric.change > 0 ? '+' : ''}{metric.change.toFixed(1)}%
                  </span>
                </div>
              )}
              <p className="text-xs text-slate-500 font-odia mt-1">{metric.labelOdia}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Chart Visualization */}
      {report.chartData && (
        <div className="glass-card rounded-2xl p-4 sm:p-6">
          <h3 className="text-slate-800 mb-4 flex items-center gap-2">
            {report.chartData.type === 'bar' && <BarChart3 size={20} />}
            {report.chartData.type === 'line' && <LineChart size={20} />}
            {report.chartData.type === 'pie' && <PieChart size={20} />}
            {report.chartData.type === 'area' && <LineChart size={20} />}
            Data Visualization
          </h3>
          
          <div className="bg-white/50 rounded-xl p-4">
            <ResponsiveContainer width="100%" height={300}>
              {report.chartData.type === 'bar' && (
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="name" stroke="#64748b" style={{ fontSize: '12px' }} />
                  <YAxis stroke="#64748b" style={{ fontSize: '12px' }} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'white', 
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                      fontSize: '12px'
                    }} 
                  />
                  <Legend wrapperStyle={{ fontSize: '12px' }} />
                  {report.chartData.datasets.map((dataset, idx) => (
                    <Bar 
                      key={idx} 
                      dataKey={dataset.label} 
                      fill={dataset.color || COLORS[idx % COLORS.length]}
                      radius={[4, 4, 0, 0]}
                    />
                  ))}
                </BarChart>
              )}

              {report.chartData.type === 'line' && (
                <ReLineChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="name" stroke="#64748b" style={{ fontSize: '12px' }} />
                  <YAxis stroke="#64748b" style={{ fontSize: '12px' }} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'white', 
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                      fontSize: '12px'
                    }} 
                  />
                  <Legend wrapperStyle={{ fontSize: '12px' }} />
                  {report.chartData.datasets.map((dataset, idx) => (
                    <Line 
                      key={idx} 
                      type="monotone"
                      dataKey={dataset.label} 
                      stroke={dataset.color || COLORS[idx % COLORS.length]}
                      strokeWidth={2}
                      dot={{ r: 4 }}
                    />
                  ))}
                </ReLineChart>
              )}

              {report.chartData.type === 'pie' && (
                <RePieChart>
                  <Pie
                    data={chartData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={(entry) => `${entry.name}: ${entry.value}`}
                    outerRadius={100}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'white', 
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                      fontSize: '12px'
                    }} 
                  />
                </RePieChart>
              )}

              {report.chartData.type === 'area' && (
                <AreaChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="name" stroke="#64748b" style={{ fontSize: '12px' }} />
                  <YAxis stroke="#64748b" style={{ fontSize: '12px' }} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'white', 
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                      fontSize: '12px'
                    }} 
                  />
                  <Legend wrapperStyle={{ fontSize: '12px' }} />
                  {report.chartData.datasets.map((dataset, idx) => (
                    <Area 
                      key={idx} 
                      type="monotone"
                      dataKey={dataset.label} 
                      stroke={dataset.color || COLORS[idx % COLORS.length]}
                      fill={dataset.color || COLORS[idx % COLORS.length]}
                      fillOpacity={0.3}
                    />
                  ))}
                </AreaChart>
              )}
            </ResponsiveContainer>
          </div>
        </div>
      )}

      {/* Insights & Recommendations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
        {/* Insights */}
        <div className="glass-card rounded-2xl p-4 sm:p-6">
          <h3 className="text-slate-800 mb-4 flex items-center gap-2">
            <Lightbulb size={20} />
            Key Insights
          </h3>
          <div className="space-y-3">
            <ul className="space-y-2">
              {report.insights.map((insight, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-slate-700">
                  <CheckCircle size={16} className="text-green-600 flex-shrink-0 mt-0.5" />
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
            <div className="pt-3 border-t border-slate-200">
              <ul className="space-y-2">
                {report.insightsOdia.map((insight, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-slate-700 font-odia">
                    <CheckCircle size={16} className="text-green-600 flex-shrink-0 mt-0.5" />
                    <span>{insight}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Recommendations */}
        <div className="glass-card rounded-2xl p-4 sm:p-6">
          <h3 className="text-slate-800 mb-4 flex items-center gap-2">
            <Target size={20} />
            Recommendations
          </h3>
          <div className="space-y-3">
            <ul className="space-y-2">
              {report.recommendations.map((rec, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-slate-700">
                  <span className="text-blue-600 flex-shrink-0 mt-0.5">→</span>
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
            <div className="pt-3 border-t border-slate-200">
              <ul className="space-y-2">
                {report.recommendationsOdia.map((rec, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-slate-700 font-odia">
                    <span className="text-blue-600 flex-shrink-0 mt-0.5">→</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* Download Section */}
      <div className="glass-card rounded-2xl p-4 sm:p-6">
        <h3 className="text-slate-800 mb-4">Download Report</h3>
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
          <div className="flex-1">
            <p className="text-sm text-slate-600 mb-3">Select format to download:</p>
            <div className="flex flex-wrap gap-2">
              {report.format.map((format) => (
                <button
                  key={format}
                  onClick={() => setSelectedFormat(format)}
                  className={`px-4 py-2 rounded-xl transition-all ${
                    selectedFormat === format
                      ? 'bg-green-600 text-white'
                      : 'bg-white/70 text-slate-700 hover:bg-white border border-white/30'
                  }`}
                >
                  {format}
                </button>
              ))}
            </div>
            <p className="text-xs text-slate-500 mt-2">File size: {report.size}</p>
          </div>
          <button className="px-6 py-3 bg-gradient-to-r from-green-600 to-green-700 text-white rounded-xl hover:shadow-lg transition-all flex items-center justify-center gap-2">
            <Download size={20} />
            <span>Download {selectedFormat}</span>
          </button>
        </div>
      </div>
    </motion.div>
  );
}
